import type { Metadata } from "next";
import { cn } from "@/lib/utils";

import "@/app/globals.css";
import Nav from "@/components/Nav";
import { roboto } from "@/app/fonts";
import Footer from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
    title: "Fotograf",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <head>
                <meta name="theme-color" content="#F6F6F6" />
            </head>
            <body
                className={cn(
                    "bg-[#F6F6F6] min-h-screen text-lg font-sans antialiased",
                    roboto.variable
                )}
            >
                <NextTopLoader
                    color="#9C916A"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={3}
                    crawl={true}
                    showSpinner={false}
                    easing="ease"
                    speed={200}
                    shadow="0 0 25px #9C916A,0 0 15px #9C916A"
                    zIndex={1600}
                    showAtBottom={false}
                />
                <Nav />
                <main className="w-full overflow-x-hidden min-h-screen px-2">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
